//> output "PANIC: Invalid argument"
//> test-crash

import std/core;

func foo() -> Result!<int> {
	throw Error::EINVAL;
}

func main() -> void {
	discard must foo();
}
