//> output "PANIC: Invalid argument"
//> test-crash

import std/core;

func main() {
	panic(Error::EINVAL);
}
