//> output "Assertion failed"
//> test-crash

import std/core;

func main() -> void {
	panic(Error::EASSERTFAILED);
}
