//> output "Out of bounds array access"
//> test-crash

import std/core;

func main() -> void {
	panic(Error::EBOUNDS);
}
