import std/core;

[extern_name: "get_errno"]
extern func errno() -> &&Error;
